[project]
name = "data-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyqtgraph>=0.13.7",
    "pyside6>=6.9.0",
    "qdarkstyle>=3.2.3",
    "qt-material>=2.17",
    "qtconsole>=5.6.1",
]
