[build-system]
  build-backend = "setuptools.build_meta"
  requires = ["setuptools", "wheel"]

[project]
  dependencies = ["betterproto2-compiler>=0.4.0"]
  description = "Generated proto package"
  name = "lioptec_server"
  requires-python = ">=3.11"
  version = "1.0"
